# Neural Network made using Tensorflow

In [1]:
import math
import matplotlib.pyplot as plt
import keras
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from datetime import timedelta

In [2]:
df=pd.read_csv("C:\\Users\\User\\Desktop\\Drive D\\New folder\\ML\\Completed\\AirBnb.csv")
print('Number of rows and columns:', df.shape)
df.head(5)

Number of rows and columns: (777, 7)


Date        Open        High         Low       Close   Adj Close  \
0  2020-12-10  146.000000  165.000000  141.250000  144.710007  144.710007   
1  2020-12-11  146.550003  151.500000  135.100006  139.250000  139.250000   
2  2020-12-14  135.000000  135.300003  125.160004  130.000000  130.000000   
3  2020-12-15  126.690002  127.599998  121.500000  124.800003  124.800003   
4  2020-12-16  125.830002  142.000000  124.910004  137.990005  137.990005   

     Volume  
0  70447500  
1  26980800  
2  16966100  
3  10914400  
4  20409600

In [3]:
df = df[['Date','Adj Close']]
df

Date   Adj Close
0    2020-12-10  144.710007
1    2020-12-11  139.250000
2    2020-12-14  130.000000
3    2020-12-15  124.800003
4    2020-12-16  137.990005
..          ...         ...
772  2024-01-08  140.080002
773  2024-01-09  139.529999
774  2024-01-10  139.759995
775  2024-01-11  139.449997
776  2024-01-12  137.139999

[777 rows x 2 columns]

In [4]:
training_set = df.iloc[:622, 1:2].values
test_set = df.iloc[622:, 1:2].values

In [5]:
test_set.size

155

In [6]:
# Creating a data structure with 60 time-steps and 1 output
X_train = []
y_train = []
for i in range(10, 622):
    X_train.append(training_set[i-10:i, 0])
    y_train.append(training_set[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
#(740, 60, 1)

In [7]:
#Creating the LSTM Model
model = Sequential()
model.add(LSTM(400,return_sequences=True,input_shape=(X_train.shape[1], 1)))
model.add(LSTM(400))
model.add(Dense(200))


model.add(Dense(1))


# Defining the optimizer with the learning rate
learning_rate = 0.0001
optimizer = Adam(learning_rate=learning_rate,beta_2=0.999,epsilon=1e-07)

#Compiling the model
model.compile(loss='mse',optimizer=optimizer)

In [8]:
#Training the model
with(tf.device("CPU")):
    history=model.fit(X_train,y_train,epochs=100,batch_size=1)

Epoch 1/100
612/612 [==============================] - 31s 47ms/step - loss: 2413.1797
Epoch 2/100
612/612 [==============================] - 29s 47ms/step - loss: 82.7869
Epoch 3/100
612/612 [==============================] - 29s 47ms/step - loss: 50.0300
Epoch 4/100
612/612 [==============================] - 29s 48ms/step - loss: 52.2027
Epoch 5/100
612/612 [==============================] - 29s 48ms/step - loss: 40.9879
Epoch 6/100
612/612 [==============================] - 29s 48ms/step - loss: 41.3596
Epoch 7/100
612/612 [==============================] - 29s 48ms/step - loss: 38.3012
Epoch 8/100
612/612 [==============================] - 30s 48ms/step - loss: 38.5082
Epoch 9/100
612/612 [==============================] - 29s 47ms/step - loss: 35.7853
Epoch 10/100
612/612 [==============================] - 29s 48ms/step - loss: 39.3617
Epoch 11/100
612/612 [==============================] - 29s 48ms/step - loss: 35.0525
Epoch 12/100
612/612 [==============================] - 30s 4

In [9]:
# Getting the predicted stock price of 2017
dataset_train = df.iloc[:622, 1:2]
dataset_test = df.iloc[622:, 1:2]
dataset_total = pd.concat((dataset_train, dataset_test), axis = 0)
inputs = dataset_total[len(dataset_total) - len(dataset_test) - 10:].values
X_test = []
y_test=[]
for i in range(10, 155):
    X_test.append(inputs[i-10:i, 0])
    y_test.append(inputs[i, 0])
X_test, y_test = np.array(X_test), np.array(y_test)
#X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
#y_test = np.reshape(y_test,(y_test.shape[0],y_test.shape[1],1))
print(X_test.shape)
# (459, 60, 1)

(145, 10, 1)


In [10]:
with(tf.device("CPU")):
    predicted_value = model.predict(X_test)

5/5 [==============================] - 1s 27ms/step


In [11]:
predicted_value.shape

(145, 1)

In [12]:
dataset_test.shape

(155, 1)

In [13]:
y_test

array([118.059998, 115.690002, 117.300003, 116.550003, 115.5     ,
       117.860001, 124.589996, 124.900002, 125.139999, 127.849998,
       128.679993, 126.449997, 127.459999, 127.959999, 124.730003,
       123.129997, 127.889999, 127.629997, 125.099998, 128.160004,
       132.350006, 131.690002, 128.160004, 130.320007, 131.710007,
       137.539993, 137.020004, 140.089996, 143.339996, 145.360001,
       146.529999, 145.535004, 145.279999, 148.770004, 147.619995,
       148.649994, 150.169998, 148.5     , 153.330002, 152.190002,
       148.910004, 144.559998, 140.880005, 140.169998, 143.199997,
       139.550003, 137.869995, 135.970001, 133.679993, 133.240005,
       129.850006, 128.830002, 127.989998, 125.059998, 124.      ,
       127.080002, 128.130005, 124.720001, 125.790001, 126.154999,
       132.25    , 130.610001, 131.550003, 132.690002, 142.289993,
       141.770004, 143.270004, 145.820007, 147.330002, 147.5     ,
       144.714996, 144.119995, 142.75    , 142.550003, 141.850

In [14]:
predicted_value

array([[117.00699 ],
       [122.02074 ],
       [119.42937 ],
       [119.77336 ],
       [120.48774 ],
       [119.0173  ],
       [121.51453 ],
       [128.30882 ],
       [127.18951 ],
       [126.14839 ],
       [129.19597 ],
       [130.00047 ],
       [127.47798 ],
       [129.14839 ],
       [130.47252 ],
       [127.36321 ],
       [125.3344  ],
       [130.56178 ],
       [130.10222 ],
       [126.48103 ],
       [129.71303 ],
       [134.72992 ],
       [134.64934 ],
       [132.07228 ],
       [134.99245 ],
       [137.49013 ],
       [142.6607  ],
       [141.31856 ],
       [144.27605 ],
       [148.07794 ],
       [149.45781 ],
       [150.71198 ],
       [150.04204 ],
       [150.16154 ],
       [154.00989 ],
       [151.94203 ],
       [152.5654  ],
       [154.71275 ],
       [152.45198 ],
       [157.68883 ],
       [156.31831 ],
       [152.25197 ],
       [148.6945  ],
       [145.11108 ],
       [144.47342 ],
       [147.6898  ],
       [143.04913 ],
       [141.3

In [15]:
mape = np.mean(np.abs((y_test - predicted_value) / y_test) * 100, axis=1)
mape

array([11.08070361,  8.29443805,  9.63393928,  9.44867023,  9.07196547,
        9.86160089,  8.54887588,  6.16312366,  6.31247904,  6.56172934,
        6.14631477,  6.15932528,  6.25733825,  6.14582914,  6.18080044,
        6.27871555,  6.82472324,  6.18550092,  6.16360615,  6.46979704,
        6.15173107,  6.7832733 ,  6.76477939,  6.29881274,  6.84352469,
        7.52131754,  9.59020356,  8.96090505, 10.45226908, 12.82990374,
       13.8191829 , 14.74454416, 14.2479254 , 14.3356268 , 17.2176546 ,
       15.65853287, 16.12512568, 17.75260893, 16.03982254, 20.01771311,
       18.97460848, 15.88939155, 13.26171878, 10.93068348, 10.56185761,
       12.55946498,  9.78766813,  8.9678855 ,  8.66005932,  7.84830699,
        7.79016385,  6.83128881,  6.59244653,  6.54825458,  6.17289157,
        6.19355919,  6.1711073 ,  6.19353748,  6.49548127,  6.30675936,
        6.15423108,  6.72688808,  6.40677468,  6.66394367,  7.48444716,
       12.35186119, 11.08446417, 11.81390902, 14.58539292, 15.47

In [16]:
# Assuming 'mape' is the array of MAPE values
overall_mape = np.mean(mape)
print("Overall MAPE:", overall_mape)

Overall MAPE: 9.227928973677278


In [17]:
# Extend the dataset to include the future time period
dataset_extended = pd.concat([dataset_total, pd.DataFrame(inputs)], axis=0)

# Generate future time steps for prediction
future_steps = 5 * 12  # 5 years * 4 quarters/year

# Initialize an array to store the predicted values
predictions = []

with(tf.device("CPU")):
# Make predictions for each future time step
    for _ in range(future_steps):
        # Reshape the input data to match the model's input shape
        input_data = dataset_extended[-662:].values
        input_data = input_data.reshape(1, -1, 1)

        # Use the model to make predictions
        predicted_value = model.predict(input_data)

        # Append the predicted value to the predictions array
        predictions.append(predicted_value[0, 0])

        # Update the input data with the predicted value for the next time step
        dataset_extended = pd.concat([dataset_extended, pd.DataFrame(predicted_value)], axis=0)

# Convert the predictions array to a numpy array
predictions = np.array(predictions)

# Print the predicted values for the future period
print(predictions)

1/1 [==============================] - 0s 225ms/step
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan]


In [18]:
# Assuming 'df' is your DataFrame with a datetime index and 'Adj Close' is the time series data
# Also, assuming 'model' is your trained LSTM model

# Extract the time series data
time_series_data = df['Adj Close'].values.reshape(-1, 1)

# Set the sequence length (number of time steps to look back)
sequence_length = 10

# Create input sequences for the last 'sequence_length' data points in the time series
input_sequence = time_series_data[-sequence_length:].reshape(1, -1, 1)

with(tf.device("CPU")):
    # Make the prediction
    predicted_scaled_value = model.predict(input_sequence)

print(f'Predicted Adj Close for the next time step: {predicted_scaled_value}')


1/1 [==============================] - 0s 26ms/step
Predicted Adj Close for the next time step: [[142.09946]]


In [19]:
# Assuming 'df' is your DataFrame with a datetime index and 'Adj Close' is the time series data
# Also, assuming 'model' is your trained LSTM model

# Extract the time series data
time_series_data = df['Adj Close'].values.reshape(-1, 1)


# Set the sequence length (number of time steps to look back)
sequence_length = 50

# Function to make predictions into the future

def make_future_predictions(model, initial_sequence, num_steps):
    with(tf.device("CPU")):
        predictions = []
        current_sequence = initial_sequence.copy()

        for _ in range(num_steps):
            # Make a prediction for the next time step
            next_scaled_value = model.predict(current_sequence.reshape(1, -1, 1))

            # Append the predicted value to the list of predictions
            predictions.append(next_scaled_value[0,0])

            # Update the current sequence by removing the first element and appending the predicted value
            current_sequence = np.concatenate([current_sequence[1:], next_scaled_value.reshape(1, -1)])

        return np.array(predictions)

In [20]:
# Set the number of steps (days) to predict into the future (e.g., 10 years = 3650 days)
num_steps = 100

# Use the last 'sequence_length' data points as the initial sequence
initial_sequence = time_series_data[-sequence_length:]

# Make predictions into the future
future_predictions_scaled = make_future_predictions(model, initial_sequence, num_steps)

# Create a DataFrame with the future dates and predicted values
last_date = pd.to_datetime(df.index[-1])
future_dates = pd.date_range(start=last_date + timedelta(days=1), periods=num_steps, freq='D')
future_df = pd.DataFrame(index=future_dates, columns=['Predicted Adj Close'])
future_df['Predicted Adj Close'] = future_predictions_scaled  # Use scaled values for consistency


# Concatenate the original DataFrame with the DataFrame containing future predictions
final_df = pd.concat([df, future_df])
final_df

1/1 [==============================] - 0s 26ms/step


Date   Adj Close  Predicted Adj Close
0                              2020-12-10  144.710007                  NaN
1                              2020-12-11  139.250000                  NaN
2                              2020-12-14  130.000000                  NaN
3                              2020-12-15  124.800003                  NaN
4                              2020-12-16  137.990005                  NaN
...                                   ...         ...                  ...
1970-04-07 00:00:00.000000776         NaN         NaN           119.916977
1970-04-08 00:00:00.000000776         NaN         NaN           119.916870
1970-04-09 00:00:00.000000776         NaN         NaN           119.916725
1970-04-10 00:00:00.000000776         NaN         NaN           119.916611
1970-04-11 00:00:00.000000776         NaN         NaN           119.916519

[877 rows x 3 columns]

In [21]:
future_predictions_scaled

array([130.83057 , 125.86276 , 122.45451 , 120.818535, 120.330124,
       120.29675 , 120.39318 , 120.4904  , 120.551   , 120.57709 ,
       120.5803  , 120.57143 , 120.55745 , 120.54099 , 120.52353 ,
       120.50628 , 120.49111 , 120.47799 , 120.46517 , 120.45136 ,
       120.43756 , 120.42304 , 120.40673 , 120.38884 , 120.36989 ,
       120.350395, 120.33018 , 120.30919 , 120.28786 , 120.266365,
       120.244774, 120.223526, 120.202545, 120.182045, 120.16257 ,
       120.144325, 120.12714 , 120.11084 , 120.09564 , 120.08178 ,
       120.0693  , 120.058075, 120.04782 , 120.038216, 120.028625,
       120.01808 , 120.00603 , 119.99286 , 119.979195, 119.966125,
       119.95466 , 119.94554 , 119.93896 , 119.934685, 119.93221 ,
       119.93089 , 119.930176, 119.92967 , 119.92919 , 119.92875 ,
       119.928246, 119.92774 , 119.92724 , 119.92667 , 119.92616 ,
       119.92566 , 119.92517 , 119.92469 , 119.92417 , 119.92375 ,
       119.923294, 119.922874, 119.922485, 119.92209 , 119.921

# Neural Network made using PyTorch

In [22]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler

In [23]:
df

Date   Adj Close
0    2020-12-10  144.710007
1    2020-12-11  139.250000
2    2020-12-14  130.000000
3    2020-12-15  124.800003
4    2020-12-16  137.990005
..          ...         ...
772  2024-01-08  140.080002
773  2024-01-09  139.529999
774  2024-01-10  139.759995
775  2024-01-11  139.449997
776  2024-01-12  137.139999

[777 rows x 2 columns]

In [24]:
# Normalize data
#scaler = MinMaxScaler(feature_range=(-1, 1))
vals = df['Adj Close'].values.reshape(-1,1)
#data_normalized = scaler.fit_transform(vals)
data_normalized = vals

In [25]:
# Convert data to PyTorch tensor
data_tensor = torch.Tensor(data_normalized).unsqueeze(2)  # Add a third dimension (features)

In [26]:
# Split data into training and testing sets
train_data = data_tensor[:622]
test_data = data_tensor[622:]

In [27]:
# Define LSTM model
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(LSTMModel, self).__init__()
        self.lstm = nn.LSTM(input_size=input_size, 
                            hidden_size=hidden_size, 
                            num_layers=num_layers, 
                            batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, _ = self.lstm(x)
        out = self.fc(out[:, -1, :])
        return out

In [28]:
# Initialize model
input_size = 1
hidden_size = 64
num_layers = 2
output_size = 1
model = LSTMModel(input_size, hidden_size, num_layers, output_size)

In [29]:
# Loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [30]:
# Training loop
num_epochs = 6775
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(train_data)
    
    # Reshape target data to match the shape of outputs
    target = train_data[:, -1, :].unsqueeze(1)
    target = target.reshape(-1,1)

    loss = criterion(outputs, target)

    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 1 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Set the model to evaluation mode

Epoch [1/6775], Loss: 20909.7148
Epoch [2/6775], Loss: 20904.2871
Epoch [3/6775], Loss: 20898.9688
Epoch [4/6775], Loss: 20893.7656
Epoch [5/6775], Loss: 20888.6562
Epoch [6/6775], Loss: 20883.5742
Epoch [7/6775], Loss: 20878.4316
Epoch [8/6775], Loss: 20873.1699
Epoch [9/6775], Loss: 20867.7422
Epoch [10/6775], Loss: 20862.1191
Epoch [11/6775], Loss: 20856.2695
Epoch [12/6775], Loss: 20850.1758
Epoch [13/6775], Loss: 20843.8047
Epoch [14/6775], Loss: 20837.1387
Epoch [15/6775], Loss: 20830.1543
Epoch [16/6775], Loss: 20822.8223
Epoch [17/6775], Loss: 20815.1152
Epoch [18/6775], Loss: 20807.0117
Epoch [19/6775], Loss: 20798.4766
Epoch [20/6775], Loss: 20789.4863
Epoch [21/6775], Loss: 20780.0156
Epoch [22/6775], Loss: 20770.0391
Epoch [23/6775], Loss: 20759.5273
Epoch [24/6775], Loss: 20748.4609
Epoch [25/6775], Loss: 20736.8066
Epoch [26/6775], Loss: 20724.5391
Epoch [27/6775], Loss: 20711.6152
Epoch [28/6775], Loss: 20698.0039
Epoch [29/6775], Loss: 20683.6582
Epoch [30/6775], Loss: 

In [31]:
# Set the model to evaluation mode
model.eval()

# Make predictions on the test data
with torch.no_grad():
    predictions = model(test_data)
    predictions_squeezed = torch.squeeze(predictions, dim=1)  # Squeeze the extra dimension

# Reshape target test data to match the shape of predictions
target_test = test_data.squeeze(2)

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(target_test.numpy(), predictions_squeezed.numpy())

# Print MSE
print(f"Mean Squared Error on Test Data: {mse}")

Mean Squared Error on Test Data: 0.7860252261161804
