In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
df = pd.read_csv("D://New folder//ML//Completed//balance-scale.csv")
df.head()

Class  L-Weight  L-Distance  R-Weight  R-Distance
0     B         1           1         1           1
1     R         1           1         1           2
2     R         1           1         1           3
3     R         1           1         1           4
4     R         1           1         1           5

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Class       625 non-null    object
 1   L-Weight    625 non-null    int64 
 2   L-Distance  625 non-null    int64 
 3   R-Weight    625 non-null    int64 
 4   R-Distance  625 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 24.5+ KB


In [4]:
x = df.drop('Class',axis=1)
y = df[['Class']]

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [6]:
clf_model = DecisionTreeClassifier(criterion='gini', random_state=42, max_depth=3, min_samples_leaf=5)
clf_model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=42)

In [7]:
y_pred = clf_model.predict(x_test)

In [8]:
print(confusion_matrix(y_test,y_pred))

[[ 0  8 10]
 [ 0 62 18]
 [ 0 20 70]]


In [9]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           B       0.00      0.00      0.00        18
           L       0.69      0.78      0.73        80
           R       0.71      0.78      0.74        90

    accuracy                           0.70       188
   macro avg       0.47      0.52      0.49       188
weighted avg       0.64      0.70      0.67       188



C:\Users\User\anaconda3\envs\Research\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\anaconda3\envs\Research\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\anaconda3\envs\Research\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
target = list(df['Class'].unique())
feature_names = list(x.columns)

In [13]:
r = export_text(clf_model,feature_names=feature_names)
print(r)

|--- L-Weight <= 2.50
|   |--- R-Distance <= 1.50
|   |   |--- L-Distance <= 2.50
|   |   |   |--- class: R
|   |   |--- L-Distance >  2.50
|   |   |   |--- class: L
|   |--- R-Distance >  1.50
|   |   |--- R-Weight <= 2.50
|   |   |   |--- class: R
|   |   |--- R-Weight >  2.50
|   |   |   |--- class: R
|--- L-Weight >  2.50
|   |--- L-Distance <= 2.50
|   |   |--- R-Weight <= 2.50
|   |   |   |--- class: L
|   |   |--- R-Weight >  2.50
|   |   |   |--- class: R
|   |--- L-Distance >  2.50
|   |   |--- R-Distance <= 3.50
|   |   |   |--- class: L
|   |   |--- R-Distance >  3.50
|   |   |   |--- class: L

