In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test =  x_train/255, x_test/255

11490434/11490434 [==============================] - 111s 10us/step


In [4]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                   tf.keras.layers.Dense(128,activation='relu'),
                                   tf.keras.layers.Dropout(0.2),
                                   tf.keras.layers.Dense(10)])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-1.0032722 ,  0.05366036,  0.1226189 , -0.17807682, -0.4587707 ,
         0.13446796,  0.34530583,  0.03783198, -0.69606626, -0.17824742]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.04096325, 0.11787302, 0.12628818, 0.09349152, 0.07061035,
        0.12779348, 0.15778816, 0.11602196, 0.05569449, 0.09347557]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.05734

In [8]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [9]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2987 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1466 - accuracy: 0.9562
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1107 - accuracy: 0.9662
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0884 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0749 - accuracy: 0.9766


In [10]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 2s - loss: 0.0752 - accuracy: 0.9779 - 2s/epoch - 5ms/step


[0.07516475021839142, 0.977899968624115]

In [11]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
probability_model(x_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[3.14281827e-08, 1.90390836e-09, 4.42388085e-07, 1.62702599e-05,
        5.22675445e-11, 3.71133559e-08, 8.96983090e-14, 9.99980688e-01,
        1.04208873e-07, 2.42459464e-06],
       [2.24503985e-10, 1.23066144e-04, 9.99690652e-01, 1.82915450e-04,
        5.17328814e-17, 3.27999578e-06, 2.65542005e-10, 3.89444404e-15,
        1.42470810e-07, 5.14101099e-15],
       [1.26541210e-07, 9.98928130e-01, 6.68569846e-05, 2.64313712e-05,
        2.28596673e-06, 2.28848558e-06, 1.12003045e-05, 8.62291199e-04,
        9.95529408e-05, 7.77254741e-07]], dtype=float32)>