# Variables in Tensorflow

In [1]:
import tensorflow as tf

In [2]:
# Disable eager execution
tf.compat.v1.disable_eager_execution()

In [3]:
zero = tf.Variable(0) #This is a variable

In [4]:
one = tf.constant(1) #This is a constant

In [5]:
new_value = tf.add(zero, one)

In [6]:
update = tf.compat.v1.assign(zero, new_value) #Variable value can be changed.

* We cannot update the value of the constant and when we try to do that; tensorflow throws an error.

In [7]:
init_op = tf.compat.v1.global_variables_initializer()

In [8]:
sess = tf.compat.v1.Session()

In [9]:
sess.run(init_op) #Initializing the variables

In [10]:
print(sess.run(zero))

0


In [11]:
for _ in range(5):
    sess.run(update)
    print(sess.run(zero))

1
2
3
4
5


* The underscore **_** is commonly used as a variable name in Python when the variable is only needed temporarily and its value is not going to be used. In other words, it's a convention to indicate that the value assigned to _ will be ignored. This is especially useful in loops and unpacking where the variable's value is not important for the logic of the code.

# String Opeerations

In [12]:
hello = tf.constant("hello")

In [13]:
world = tf.constant("world")

In [14]:
helloworld = tf.add(hello,world)

In [15]:
print(sess.run(helloworld))

b'helloworld'


# Placeholder

In [16]:
a = tf.compat.v1.placeholder(tf.float32)

In [17]:
b = a * 2

In [18]:
#feeding a placeholder with scalar
result = sess.run(b, feed_dict={a:3})

In [19]:
print(result)

6.0


In [20]:
#feeding a placeholder with vector of rank 1
result = sess.run(b, feed_dict={a:[3,4,5]})
print(result)

[ 6.  8. 10.]


In [22]:
#feeding a placeholder with multidimensional vector
dictionary = {a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}
result = sess.run(b, feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [23]:
sess.close()

In [26]:
with tf.compat.v1.Session() as sess:
    result = sess.run(hello+world)
    print(result)

b'helloworld'


In [28]:
graph = tf.compat.v1.get_default_graph()

In [29]:
graph.get_operations()

[<tf.Operation 'Variable/Initializer/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VarHandleOp>,
 <tf.Operation 'Variable/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>,
 <tf.Operation 'Variable/Assign' type=AssignVariableOp>,
 <tf.Operation 'Variable/Read/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'Add' type=AddV2>,
 <tf.Operation 'AssignVariableOp' type=AssignVariableOp>,
 <tf.Operation 'ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add_2' type=Add>]